- name: update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: install apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ item.package_name }}"
    state: "{{ item.state }}"
  with_items:
    "{{ apt_packages }}"

- name: add nvim ppa
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present

- name: download ripgrep binary
  become: true
  ansible.builtin.get_url:
    url: https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
    dest: /etc/
    mode: 770
  register: binary_path

- name: output last value
  ansible.builtin.debug:
    msg: "{{ binary_path }}"


- name: install ripgrep
  become: true
  ansible.builtin.apt:
    deb: "{{ binary_path.dest }}"
