- name: add lazygit repo
  apt_repository:
    repo: ppa:lazygit-team/release
    state: present

- name: install apt packages
  become: true
  apt: 
    name: "{{ item.package_name }}"
    state: "{{ item.state }}"
  with_items:
    "{{ apt_packages }}"

- name: download ripgrep binary
  get_url:
    url: https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
    dest: /tmp/thorntonmc/dotfiles/install/ripgrep_13.0.0_amd64.deb
    mode: 770

- name: install ripgrep
  apt:
    deb: /tmp/thorntonmc/dotfiles/install/ripgrep_13.0.0_amd64.deb
