- name: add lazygit repo
  apt_repository:
    repo: ppa:lazygit-team/release
    state: present

- name: install apt packages
  apt: 
    name: "{{ item.package_name }}"
    state: "{{ item.state }}"
    become: true
  with_items:
    "{{ packages }}"
