- name: install dnf-plugins-core
  become: true
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present

- name: enable coprs for lazygit
  become: true
  ansible.builtin.shell: |
    dnf -y copr enable atim/lazygit

- name: add 1password key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://downloads.1password.com/linux/keys/1password.asc

- name: add 1password yum repository
  become: true
  ansible.builtin.yum_repository:
    state: present
    name: 1password
    description: 1password
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
    enabled: true


- name: install dnf packages
  become: true
  ansible.builtin.dnf:
    name: "{{ item.package_name }}"
    state: "{{ item.state }}"
  with_items:
    "{{ dnf_packages }}"

