- name: install dnf-plugins-core
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present

- name: enable coprs for lazygit
  become: true
  ansible.builtin.shell: |
    dnf -y copr enable atim/lazygit

- name: install dnf packages
  become: true
  ansible.builtin.dnf:
    name: "{{ item.package_name }}"
    state: "{{ item.state }}"
  with_items:
    "{{ dnf_packages }}"

