---
- include_tasks:
    file: apt.yml
    apply:
      tags: packages
  when: manager == "apt"
  tags: packages

- include_tasks:
    file: dnf.yml
    apply:
      tags: packages
  when: manager == "dnf"
  tags: packages

- include_tasks:
    file: pacman.yml
    apply:
      tags: packages
  when: manager == "pacman"
  tags: packages

- include_tasks:
    file: yay.yml
    apply:
      tags: packages
  when: manager == "yay"
  tags: packages
