---
- name: dev-machine
  hosts: localhost
  vars:
    home: "{{ ansible_facts['user_dir'] }}"
    manager: "{{ ansible_facts['pkg_mgr'] }}"
  tasks:
    - name: install packages
      ansible.builtin.include_role:
        name: packages
      vars:
        manager: "{{ manager }}"
      tags: packages

    - name: enable bluetooth
      become: true
      ansible.builtin.systemd:
        name: bluetooth
        enabled: true
        state: started

    - name: setup rootless podman
      ansible.builtin.include_role:
        name: rootless-podman
      tags: rootless-podman

    - name: create {{ home }}/.local
      ansible.builtin.file:
        state: directory
        dest: "{{ home }}/.local"
        mode: 0755
      tags: dotfiles

    - name: get app dir
      ansible.builtin.shell: |
          dirname {{ playbook_dir }}
      register: dirname
      tags: dotfiles

    - name: set app dir
      set_fact:
        appdir: "{{ dirname.stdout }}"
      tags: dotfiles

    - name: symlink dotfiles
      become: true
      ansible.builtin.file:
        state: link
        src: "{{ item.src }}"
        dest: "{{ item.dest}}"
        force: true
      with_items:
        - {src: "{{ appdir }}/.vimrc", dest: "{{ home }}/.vimrc"}
        - {src: "{{ appdir }}/.vim", dest: "{{ home }}/.vim"}
        - {src: "{{ appdir }}/.bashrc", dest: "{{ home }}/.bashrc"}
        - {src: "{{ appdir }}/.bash", dest: "{{ home }}/.bash"}
        - {src: "{{ appdir }}/.zshrc", dest: "{{ home }}/.zshrc"}
        - {src: "{{ appdir }}/.zsh", dest: "{{ home }}/.zsh"}
        - {src: "{{ appdir }}/.local/scripts", dest: "{{ home }}/.local/scripts"}
        - {src: "{{ appdir }}/.gitconfig", dest: "{{ home }}/.gitconfig"}
        - {src: "{{ appdir }}/.gitconfig-work", dest: "{{ home }}/.gitconfig-work"}
        - {src: "{{ appdir }}/logid.cfg", dest: "/etc/logid.cfg"}
        - {src: "{{ appdir }}/.config/i3", dest: "{{ home }}/.config/i3"}
        - {src: "{{ appdir }}/.config/nvim", dest: "{{ home }}/.config/nvim"}
        - {src: "{{ appdir }}/.config/alacritty", dest: "{{ home }}/.config/alacritty"}
        - {src: "{{ appdir }}/.config/polybar", dest: "{{ home }}/.config/polybar"}
      tags: dotfiles
