---
- name: macOS dev-machine
  hosts: localhost

  tasks:
  - name: install go
    homebrew:
      name: go
      state: present
  - name: install nvim
    homebrew:
      name: neovim
      state: present
