---
apt_packages:
  - {package_name: "build-essential", state: "present"}
  - {package_name: "curl", state: "present"}
  - {package_name: "coreutils", state: "present"}
  - {package_name: "net-tools", state: "present"}
  - {package_name: "neovim", state: "present"}
  - {package_name: "podman", state: "present"}
  - {package_name: "tldr", state: "present"}

dnf_packages:
  - {package_name: "1password", state: "present"}
  - {package_name: "alacritty", state: "present"}
  - {package_name: "jq", state: "present"}
  - {package_name: "lazygit", state: "present"}
  - {package_name: "neovim", state: "present"}
  - {package_name: "procps-ng", state: "present"}
  - {package_name: "ripgrep", state: "present"}
  - {package_name: "slirp4netns", state: "present"}
  - {package_name: "tldr", state: "present"}
  - {package_name: "ShellCheck", state: "present"}
  - {package_name: "NetworkManager-strongswan", state: "present"}
  - {package_name: "NetworkManager-l2tp", state: "present"}
  - {package_name: "go", state: "present"}
  - {package_name: "golang-x-tools-gopls", state: "present"}
  - {package_name: "gcc-g++", state: "present"}
  - {package_name: "cmake", state: "present"}
  - {package_name: "libevdev-devel", state: "present"}
  - {package_name: "systemd-devel", state: "present"}
  - {package_name: "libconfig-devel", state: "present"}
  - {package_name: "yamllint", state: "present"}

pacman_packages:
  - {package_name: "alacritty", state: "present"}
  - {package_name: "base-devel", state: "present"}
  - {package_name: "bluez", state: "present"}
  - {package_name: "bluez-utils", state: "present"}
  - {package_name: "blueberry", state: "present"}
  - {package_name: "buildah", state: "present"}
  - {package_name: "cmake", state: "present"}
  - {package_name: "fd", state: "present"}
  - {package_name: "firefox", state: "present"}
  - {package_name: "github-cli", state: "present"}
  - {package_name: "go", state: "present"}
  - {package_name: "gopls", state: "present"}
  - {package_name: "jq", state: "present"}
  - {package_name: "lazygit", state: "present"}
  - {package_name: "libconfig", state: "present"}
  - {package_name: "neofetch", state: "present"}
  - {package_name: "neovim", state: "present"}
  - {package_name: "networkmanager-l2tp", state: "present"}
  - {package_name: "nodejs", state: "present"}
  - {package_name: "noto-fonts-emoji", state: "present"}
  - {package_name: "npm", state: "present"}
  - {package_name: "podman", state: "present"}
  - {package_name: "python-pip", state: "present"}
  - {package_name: "ripgrep", state: "present"}
  - {package_name: "shellcheck", state: "present"}
  - {package_name: "shfmt", state: "present"}
  - {package_name: "spotifyd", state: "present"}
  - {package_name: "slirp4netns", state: "present"}
  - {package_name: "networkmanager-strongswan", state: "present"}
  - {package_name: "terraform", state: "present"}
  - {package_name: "tldr", state: "present"}
  - {package_name: "xf86-video-intel", state: "absent"}
  - {package_name: "yamllint", state: "present"}
  - {package_name: "zsh", state: "present"}

yay_packages:
  - {package_name: "1password", state: "present"}
  - {package_name: "argo", state: "present"}
  - {package_name: "goland", state: "present"}
  - {package_name: "spotify", state: "present"}
  - {package_name: "slack-desktop", state: "present"}
  - {package_name: "visual-studio-code-bin", state: "present"}
  - {package_name: "zoom", state: "present"}
